// Course data for public pages
const COURSES_DATA = [
  {
    id: "1",
    title: "Combate a Incêndios Básico",
    description: "Aprenda as técnicas fundamentais de combate a incêndios e salvamento.",
    thumbnail: "firefighter-training-basic.jpg",
    duration: 480,
    modulesCount: 6,
    level: "Básico",
  },
  {
    id: "2",
    title: "Primeiros Socorros Avançados",
    description: "Técnicas avançadas de atendimento pré-hospitalar e emergências médicas.",
    thumbnail: "first-aid-emergency.jpg",
    duration: 360,
    modulesCount: 5,
    level: "Intermediário",
  },
  {
    id: "3",
    title: "Resgate em Altura",
    description: "Operações de salvamento em locais elevados e técnicas de rapel.",
    thumbnail: "rope-rescue-height.jpg",
    duration: 420,
    modulesCount: 6,
    level: "Avançado",
  },
  {
    id: "4",
    title: "Prevenção e Investigação de Incêndios",
    description: "Técnicas de prevenção, análise de riscos e investigação de causas de incêndios.",
    thumbnail: "fire-investigation.jpg",
    duration: 300,
    modulesCount: 4,
    level: "Avançado",
  },
  {
    id: "5",
    title: "Resgate Veicular",
    description: "Técnicas de desencarceramento e salvamento em acidentes de trânsito.",
    thumbnail: "vehicle-rescue.jpg",
    duration: 360,
    modulesCount: 5,
    level: "Intermediário",
  },
  {
    id: "6",
    title: "Materiais Perigosos (HAZMAT)",
    description: "Identificação, contenção e manejo de produtos químicos perigosos.",
    thumbnail: "hazmat-training.jpg",
    duration: 400,
    modulesCount: 5,
    level: "Avançado",
  },
  {
    id: "7",
    title: "Salvamento Aquático",
    description: "Técnicas de resgate em ambientes aquáticos e enchentes.",
    thumbnail: "water-rescue.jpg",
    duration: 320,
    modulesCount: 4,
    level: "Intermediário",
  },
  {
    id: "8",
    title: "Liderança e Comando de Operações",
    description: "Gestão de equipes e coordenação de operações de emergência.",
    thumbnail: "leadership-command.jpg",
    duration: 280,
    modulesCount: 4,
    level: "Avançado",
  },
]

const MODULES_DATA = [
  {
    id: "1",
    courseId: "1",
    title: "Introdução ao Combate a Incêndios",
    description: "Fundamentos e teoria do fogo",
    lessons: [
      { id: "1", title: "Teoria do Fogo", contentType: "video", duration: 30 },
      { id: "2", title: "Classes de Incêndio", contentType: "video", duration: 25 },
      { id: "3", title: "Química da Combustão", contentType: "reading", duration: 20 },
      { id: "4", title: "Manual de Segurança", contentType: "pdf", duration: 45 },
    ],
  },
  {
    id: "2",
    courseId: "1",
    title: "Equipamentos de Proteção",
    description: "EPIs e equipamentos essenciais",
    lessons: [
      { id: "5", title: "Equipamentos de Proteção Individual", contentType: "video", duration: 35 },
      { id: "6", title: "Inspeção de EPIs", contentType: "video", duration: 28 },
      { id: "7", title: "Exercício Prático: Vestimenta", contentType: "exercise", duration: 30 },
    ],
  },
  {
    id: "3",
    courseId: "1",
    title: "Técnicas de Extinção",
    description: "Métodos e técnicas para combater diferentes tipos de incêndio",
    lessons: [
      { id: "8", title: "Métodos de Extinção", contentType: "video", duration: 40 },
      { id: "9", title: "Uso de Extintores", contentType: "video", duration: 35 },
      { id: "10", title: "Mangueiras e Esguichos", contentType: "video", duration: 38 },
      { id: "11", title: "Exercício: Simulação de Combate", contentType: "exercise", duration: 45 },
    ],
  },
  {
    id: "4",
    courseId: "1",
    title: "Ventilação e Controle de Fumaça",
    description: "Técnicas para controlar e remover fumaça",
    lessons: [
      { id: "12", title: "Princípios da Ventilação", contentType: "video", duration: 32 },
      { id: "13", title: "Ventilação Natural vs Forçada", contentType: "reading", duration: 25 },
      { id: "14", title: "Técnicas de Ventilação Tática", contentType: "video", duration: 42 },
    ],
  },
  {
    id: "5",
    courseId: "1",
    title: "Busca e Salvamento",
    description: "Técnicas de localização e resgate de vítimas",
    lessons: [
      { id: "15", title: "Técnicas de Busca Primária", contentType: "video", duration: 38 },
      { id: "16", title: "Busca Secundária", contentType: "video", duration: 30 },
      { id: "17", title: "Técnicas de Remoção de Vítimas", contentType: "video", duration: 35 },
      { id: "18", title: "Exercício: Busca em Ambiente Escuro", contentType: "exercise", duration: 40 },
    ],
  },
  {
    id: "6",
    courseId: "1",
    title: "Avaliação Final",
    description: "Teste seus conhecimentos",
    lessons: [
      { id: "19", title: "Revisão Geral", contentType: "reading", duration: 30 },
      { id: "20", title: "Avaliação Final do Curso", contentType: "quiz", duration: 60 },
    ],
  },
  {
    id: "7",
    courseId: "2",
    title: "Avaliação Inicial da Vítima",
    description: "Técnicas de triagem e avaliação primária",
    lessons: [
      { id: "21", title: "Protocolo ABCDE", contentType: "video", duration: 35 },
      { id: "22", title: "Sinais Vitais", contentType: "video", duration: 30 },
      { id: "23", title: "Exercício: Avaliação Rápida", contentType: "exercise", duration: 35 },
    ],
  },
  {
    id: "8",
    courseId: "2",
    title: "Reanimação Cardiopulmonar (RCP)",
    description: "Técnicas de RCP para adultos, crianças e bebês",
    lessons: [
      { id: "24", title: "RCP em Adultos", contentType: "video", duration: 40 },
      { id: "25", title: "Uso do DEA", contentType: "video", duration: 28 },
      { id: "26", title: "RCP Pediátrico", contentType: "video", duration: 35 },
    ],
  },
]
